fix: Don't refresh current session is the session is active (PS-333)
monta-app/kratos pull request #6
Opened 2024-06-03 12:59 UTC by maoanran

## Related issue(s)

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got the approval (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](https://github.com/ory/docs).

## Further Comments

2024-06-04 18:17 UTC, splaunov requested changes

2024-06-04 18:17 UTC, splaunov commented on selfservice/strategy/pin/login_test.go
> +	})
The test looks good

2024-06-04 18:17 UTC, splaunov commented on session/session.go
> +		return nil
Not sure if it might break "session refresh" flows.
https://www.ory.sh/docs/kratos/session-management/refresh-extend-sessions

Some existing tests have failed. Probably because of this.

2024-06-10 11:07 UTC, splaunov approved these changes
Looks good.
Make sure all tests pass with the command:

```
go test -p 1 -tags sqlite,json1 -count=1 -failfast -timeout 30m ./...
```

2024-06-10 12:08 UTC, maoanran commented
> Looks good. Make sure all tests pass with the command:
> 
> ```
> go test -p 1 -tags sqlite,json1 -count=1 -failfast -timeout 30m ./...
> ```

Thanks, there are some test failed, but not sure if it is my environment issue, do you know the failures?
```
--- FAIL: TestSettingsStrategy (1.04s)
    strategy_helper_test.go:246: Environment did not provide Ory Hydra, starting fresh.
    strategy_helper_test.go:270:
        	Error Trace:	/Users/anma/repo/kratos/selfservice/strategy/oidc/strategy_helper_test.go:270
        	            				/Users/anma/repo/kratos/selfservice/strategy/oidc/strategy_settings_test.go:60
        	Error:      	Received unexpected error:
        	            	API error (400): invalid tag format

        	            	github.com/ory/dockertest/v3.(*Pool).RunWithOptions
        	            		/Users/anma/go/pkg/mod/github.com/ory/dockertest/v3@v3.9.1/dockertest.go:413
        	            	github.com/ory/kratos/selfservice/strategy/oidc_test.newHydra
        	            		/Users/anma/repo/kratos/selfservice/strategy/oidc/strategy_helper_test.go:252
        	            	github.com/ory/kratos/selfservice/strategy/oidc_test.TestSettingsStrategy
        	            		/Users/anma/repo/kratos/selfservice/strategy/oidc/strategy_settings_test.go:60
        	            	testing.tRunner
        	            		/opt/homebrew/Cellar/go/1.22.2/libexec/src/testing/testing.go:1689
        	            	runtime.goexit
        	            		/opt/homebrew/Cellar/go/1.22.2/libexec/src/runtime/asm_arm64.s:1222
        	Test:       	TestSettingsStrategy
FAIL
FAIL	github.com/ory/kratos/selfservice/strategy/oidc	19.275s
```
```
--- FAIL: TestOAuth2Provider (1.11s)
    op_helpers_test.go:153:
        	Error Trace:	/Users/anma/repo/kratos/selfservice/strategy/password/op_helpers_test.go:153
        	            				/Users/anma/repo/kratos/selfservice/strategy/password/op_login_test.go:206
        	Error:      	Received unexpected error:
        	            	API error (400): invalid tag format

        	            	github.com/ory/dockertest/v3.(*Pool).RunWithOptions
        	            		/Users/anma/go/pkg/mod/github.com/ory/dockertest/v3@v3.9.1/dockertest.go:413
        	            	github.com/ory/kratos/selfservice/strategy/password_test.newHydra
        	            		/Users/anma/repo/kratos/selfservice/strategy/password/op_helpers_test.go:134
        	            	github.com/ory/kratos/selfservice/strategy/password_test.TestOAuth2Provider
        	            		/Users/anma/repo/kratos/selfservice/strategy/password/op_login_test.go:206
        	            	testing.tRunner
        	            		/opt/homebrew/Cellar/go/1.22.2/libexec/src/testing/testing.go:1689
        	            	runtime.goexit
        	            		/opt/homebrew/Cellar/go/1.22.2/libexec/src/runtime/asm_arm64.s:1222
        	Test:       	TestOAuth2Provider
FAIL
FAIL	github.com/ory/kratos/selfservice/strategy/password	4.619s
```

2024-06-11 14:03 UTC, splaunov commented
Try to pull hydra with this command before running tests

```
docker pull oryd/hydra:v2.2.0@sha256:6c0f9195fe04ae16b095417b323881f8c9008837361160502e11587663b37c09
```

2024-06-17 11:20 UTC, maoanran commented
Cool, the tests passed, thanks.

2024-06-17 12:18 UTC, maoanran commented
Thanks, the tests passed.

2024-06-17 14:16 UTC, merged